apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
  namespace: pr-etl-uat  # Ensure this matches the namespace where Fluent Bit should run
spec:
  replicas: 1  # You can increase the number of replicas if needed
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:1.9  # Use the latest Fluent Bit image
          volumeMounts:
            - mountPath: /tmp/fluent-bit
              name: fluent-bit-config
              subPath: fluent-bit.conf
          env:
            - name: FLUENT_BIT_OUTPUT
              value: "cloudwatch"  # Ensure logs are sent to CloudWatch
            - name: FLUENT_BIT_REGION
              value: "ap-south-1"  # Set the AWS region
            - name: FLUENT_BIT_LOG_GROUP
              value: "fluent-bit-logs"  # Set the log group name
            - name: FLUENT_BIT_LOG_STREAM
              value: "fluent-bit-stream"  # Set the log stream name
      volumes:
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config  # The ConfigMap created for Fluent Bit config
      nodeSelector:
        eks.amazonaws.com/compute-type: fargate  # Ensure Fluent Bit runs on Fargate nodes
      tolerations:
        - key: "eks.amazonaws.com/compute-type"
          operator: "Equal"
          value: "fargate"
          effect: "NoSchedule"
root@ip-10-31-29-201:~/eks#